SRC_URI = "file://${EIQA_RUNTIME_PREBUILT_TAR_PATH}"
SRC_URI[MD5SUM] = "${EIQA_RUNTIME_PREBUILD_TAR_MD5SUM}"
SRC_URI[SHA1SUM] = "${EIQA_RUNTIME_PREBUILD_TAR_SHA1SUM}"

PR = "RTM"

require eiqa-runtime-prebuilt.inc
